### ISSUE TITLE
Allow the use of a specified manifest file rather than a downloaded OCI manifest when running in manifest mode

### ISSUE THREAD

**Issue by markmorlino** [canonical/sec-cvescan#10]
Currently cvescan can only scan OCI image manifest files that it downloads. This change would enable customers can scan their own image manifest files.

The release/series would still be a required command line argument with this use case. An additional (optional?) argument should be created so that a local manifest file can be specified to scan instead of downloading a manifest.

**Comment by mattatsi** [comment]
This feature (`--file`) was available in the `latest/edge` snap channel until recently.  Can I help get it back in?

**Comment by markmorlino** [comment]
@mattatsi that option should be avaialble in the current version as `--manifest-file`

**Comment by mattatsi** [comment]
I'm not sure what else has changed.  Is there a CHANGELOG somewhere?  4 weeks ago these commands succeeded:

```
cvescan --manifest=bionic --file=$HOME/manifest.txt --priority=all
cvescan --manifest=bionic --file=$HOME/manifest.txt --priority=medium --updates
```

Now the following all fail:

```
$ cvescan --manifest=bionic --file=$HOME/manifest.txt --priority=all || true
 usage: cvescan [-h] [-c CVE-IDENTIFIER] [-p {critical,high,medium,all}] [-s]
                [-u UCT_FILE] [-m MANIFEST_FILE] [-n] [--uct-links]
                [--unresolved] [-v] [-x]
 cvescan: error: unrecognized arguments: --file=/home/builder/manifest.txt
```

```
 $ cvescan --manifest=bionic --file=$HOME/manifest.txt --priority=medium --updates
 usage: cvescan [-h] [-c CVE-IDENTIFIER] [-p {critical,high,medium,all}] [-s]
                [-u UCT_FILE] [-m MANIFEST_FILE] [-n] [--uct-links]
                [--unresolved] [-v] [-x]
 cvescan: error: unrecognized arguments: --file=/home/builder/manifest.txt --updates
```

Trying with `--manifest-file` also fails.  Seems like I need to delimit with tabs (I can do that):

```
$ cvescan --manifest=bionic --manifest-file=$HOME/manifest.txt --priority=all || true
 Traceback (most recent call last):
   File "/snap/cvescan/208/lib/python3.6/site-packages/cvescan/manifest_parser.py", line 13, in parse_manifest_file
     (pkg, version) = pkg.split("\t")
 ValueError: not enough values to unpack (expected 2, got 1)
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/snap/cvescan/208/bin/cvescan", line 30, in <module>
     sys.exit(load_entry_point('cvescan==2.0.0', 'console_scripts', 'cvescan')())
   File "/snap/cvescan/208/lib/python3.6/site-packages/cvescan/__main__.py", line 205, in main
     target_sysinfo = TargetSysInfo(opt, local_sysinfo)
   File "/snap/cvescan/208/lib/python3.6/site-packages/cvescan/target_sysinfo.py", line 7, in __init__
     self._set_from_manifest_file(opt)
   File "/snap/cvescan/208/lib/python3.6/site-packages/cvescan/target_sysinfo.py", line 13, in _set_from_manifest_file
     opt.manifest_file
   File "/snap/cvescan/208/lib/python3.6/site-packages/cvescan/manifest_parser.py", line 18, in parse_manifest_file
     "Failed to parse installed files from manifest the provided file: %s" % e
 Exception: Failed to parse installed files from manifest the provided file: not enough values to unpack (expected 2, got 1)
```

Has `--updates` been removed?

```
 $ cvescan --manifest=bionic --manifest-file=$HOME/manifest.txt --priority=medium --updates
 usage: cvescan [-h] [-c CVE-IDENTIFIER] [-p {critical,high,medium,all}] [-s]
                [-u UCT_FILE] [-m MANIFEST_FILE] [-n] [--uct-links]
                [--unresolved] [-v] [-x]
 cvescan: error: unrecognized arguments: --updates
```

In all cases, I've been using `sudo snap install cvescan --channel=latest/edge` to install.

**Comment by mssalvatore** [comment]
@mattatsi, I am, as I type this, in the process of authoring a CHANGELOG.md file.

The version of CVEScan on the edge channel has been completely rewritten. If you want to use the old version, for the time being, you can invoke CVEScan with `cvescan.sh` instead of `cvescan`. This will run the old version of the snap.

To fix the commands you mentioned above, you don't need to specify --manifest=bionic. So, your commands should look something like:

`cvescan --manifest=$HOME/manifest.txt --priority=medium`

You no longer need the --updates flag, as that is the default behavior. If you want to see more than just what updates are available, you can use the `--unresolved` flag.

**Comment by markmorlino** [comment]
Hi @mattatsi,

Version 2.0.0 was a complete rewrite. It's in --edge bacause it hasn't really been released yet. It has been published but not to a stable channel. We are planning to add a changelog I don't think it will detail all of the changes incorporated into version 2.0.0 since there are so many.

The older 1.x.x version that you are used to using is still packaged in the --edge version of snap and can now be run as `cvescan.sh.` So for the short term, you can use `cvescan.sh instead of `cvescan`. The cvescan.sh` version won't be maintained moving forward, and will eventually be removed from the snap but it is there now.

--updates is now the default behavior, and --unresolved has been added to display CVEs that have not been resolved (there is no package update available)

--manifest-file no longer requires specifiying a series with `--manifest=bionic` it will determine the series based on the version of a package that is always instealled.

Correctly formatted manifest files can be generated using `dpkg-query -W`, just redirect that output to a file.

Something like `cvescan --manifest-file ~/manifest.txt -p medium --uct-links | awk '/people.canonical.com/ {print $NF}'` should provide similar output to what you were using before. The |awk is there because the output format has changed quite a bit.

Thanks for using cvescan and thanks for taking the time to raise this issue so we can try to make it better.

**Comment by markmorlino** [comment]
oh, I guess I needed to refresh before answering, I didn't notice that @mssalvatore had already responded.

**Comment by mssalvatore** [comment]
@mattatsi, A preliminary draft of the changelog can be found here: https://github.com/canonical/sec-cvescan/blob/v2.0.0/CHANGELOG.md

In summary, CVEScan is a whole new animal. I'd recommend running `cvescan -h` to review the new options and taking a look at the new output format.

**Comment by mattatsi** [comment]
Thank you for your help!  I've got it working again and am *really* excited to see that I'll be able to install v2 with pip instead of snap!

**Comment by mssalvatore** [comment]
@mattatsi, thanks for testing out v2!

**Comment by mattatsi** [comment]
Well, I'm still using cvescan.sh (smallest change to keep our stuff working), but when v2 is released I will try it out.
