### ISSUE TITLE
cvescan crashes with OOM on machines with under 1GB RAM

### ISSUE THREAD

**Issue by kikoreis** [canonical/sec-cvescan#2]
If I run cvescan in an instance with 512MB RAM, such as an B1ls on Azure, or a t2.nano on AWS, cvescan installs fine, but dies on first run:

```
ubuntu@ermine-test:~$ sudo snap install cvescan
cvescan 1.0.3 from Mark Morlino (markmorlino) installed
ubuntu@ermine-test:~$ cvescan -v
Running as a snap, changing to '/home/ubuntu/snap/cvescan/common' directory
Downloaded files, log files and temporary reports will be in '/home/ubuntu/snap/cvescan/common'
Priority filter is 'high'
Downloading https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.eoan.cve.oval.xml.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  780k  100  780k    0     0   364k      0  0:00:02  0:00:02 --:--:--  364k
Unzipping com.ubuntu.eoan.cve.oval.xml.bz2
Running oval scan oscap oval eval --verbose WARNING --verbose-log-file debug.log --results results.xml com.ubuntu.eoan.cve.oval.xml (output logged to /home/ubuntu/snap/cvescan/common/oval.log)
/snap/cvescan/23/bin/cvescan: line 218: 32089 Killed                  oscap oval eval $VERBOSE_OSCAP_OPTIONS --results "$RESULTS" "$OVAL_FILE" > $LOG 2>&1
Error: Failed to run oval scan
```

All logfiles are empty. Here's the OOM in dmesg: https://paste.ubuntu.com/p/CtgjqFHf6S/ and here are the kernel boot messages: https://paste.ubuntu.com/p/TKBGkZdjJ2/

**Comment by kikoreis** [comment]
On my AWS t2.nano instance, it seems like there's enough memory to do the initial OVAL parse, but not to run cvescan itself:

```
ubuntu@ip-172-31-53-244:~$ cvescan  -v 
Running as a snap, changing to '/home/ubuntu/snap/cvescan/common' directory
Downloaded files, log files and temporary reports will be in '/home/ubuntu/snap/cvescan/common'
Priority filter is 'high'
Running oval scan oscap oval eval --verbose WARNING --verbose-log-file debug.log --results results.xml com.ubuntu.bionic.cve.oval.xml (output logged to /home/ubuntu/snap/cvescan/common/oval.log)
Error: Failed to run oval scan
```

Which corresponds to:

```
ubuntu@ip-172-31-53-244:~$ cat snap/cvescan/common/debug.log 
W: oscap: Can't connect: 12, Cannot allocate memory.
E: oscap: Connect: retry limit (0) reached.
```

**Comment by mssalvatore** [comment]
@kikoreis, Could you try the 2.0.0~alpha1 version of CVEScan on the edge channel and see if it resolves this issue?

**Comment by markmorlino** [comment]
xenial aws t2.nano (0.5gb ram):

installed:          2.0.0~alpha1            (202) 39MB -
ubuntu@ip-172-31-30-82:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            486          73         251           2         161         369
Swap:             0           0           0
ubuntu@ip-172-31-30-82:~$ time cvescan

Summary
------------------------------------  --------------
Ubuntu Release                        xenial
Installed Packages                    453
CVE Priority                          high or higher
Unique Packages Fixable by Patching   0
Unique CVEs Fixable by Patching       0
Vulnerabilities Fixable by Patching   0
Fixes Available by `apt-get upgrade`  0
------------------------------------  --------------



real	0m6.346s
user	0m3.144s
sys	0m0.968s

**Comment by markmorlino** [comment]
bionic aws t2.nano:

```
ubuntu@ip-172-31-25-44:~$ sudo snap install --edge cvescan
cvescan (edge) 2.0.0~alpha1 from Mark Morlino (markmorlino) installed
ubuntu@ip-172-31-25-44:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            479         105          27           0         346         361
Swap:             0           0           0
ubuntu@ip-172-31-25-44:~$ time cvescan

Summary
------------------------------------  --------------
Ubuntu Release                        bionic
Installed Packages                    498
CVE Priority                          high or higher
Unique Packages Fixable by Patching   0
Unique CVEs Fixable by Patching       0
Vulnerabilities Fixable by Patching   0
Fixes Available by `apt-get upgrade`  0
------------------------------------  --------------



real	0m8.122s
user	0m2.854s
sys	0m2.193s
```

**Comment by mssalvatore** [comment]
@markmorlino, cool! It looks like v2.0.0 will resolve this issue, as well as #31.

**Comment by markmorlino** [comment]
Focal fails on an aws t2.nano (0.5gb ram) instance but works on a t2.micro (1gb ram) instance. However, 1gb is the minimum specified the ubuntu server guide documentation for focal so we're not going to try to make it work with 0.5gb
