### ISSUE TITLE
Installs on focal but does not run on focal

### ISSUE THREAD

**Issue by BillDietrich** [canonical/sec-cvescan#37]
I installed snap cvescan version 1.0.10 rev 76 on Ubuntu desktop GNOME 20.04, but running it gives "Error: DISTRIB_CODENAME=focal in /etc/lsb-release is not trusty|xenial|bionic|eoan, not running".

**Comment by mssalvatore** [comment]
We're planning on releasing v2.0.0 which will resolve this issue.

**Comment by BillDietrich** [comment]
Is it proper to release a package that says "focal", but then when it runs, says "sorry doesn't support focal" ?  Maybe better to not release for focal until it actually supports focal.

**Comment by markmorlino** [comment]
Can you explain what you mean by 'release a package labeled "focal"' and 'better to not release for focal until it actually supports focal.' ?

It's a snap so it will likely install on lots of operating systems where it won't be supported? It would likely install on 19.04/disco and fedora, but it isn't supported there either.

I'm not aware of anything we do to label it focal, or release it for focal.

**Comment by BillDietrich** [comment]
Sorry, you're right, I must have confused it with something else.  Thought it was listed in apt as a "/focal" package, but now I see it's a snap and I installed it through the Ubuntu Software store.  Sorry.

**Comment by markmorlino** [comment]
@BillDietrich I had a go at adding focal support to the latest 1.x release and I ran into a bunch of issues with the underlying calls to oscap. I can remove the checks and get it to run on focal but it doesn't work correctly. 

Unfortunately, I think we have to wait for the release to be ready. That should happen within a few weeks.

**Comment by mssalvatore** [comment]
@BillDietrich, an alpha release of v2.0.0 has been pushed to the edge channel of the snap store. You can install it with `sudo snap install --edge cvescan` or update it with `sudo snap refresh --edge cvescan` if CVEScan is already installed.
