### ISSUE TITLE
Database files are out of date

### ISSUE THREAD

**Issue by piax93** [canonical/sec-cvescan#80]
The database files the tools uses to match CVEs are out of date. The page https://people.canonical.com/~ubuntu-security/cvescan/ shows that the files were last modified on May 3rd 2021, more than a month ago.

Were these moved to a new location?

**Comment by piax93** [comment]
This seems now to be solved.

**Comment by stevebeattie** [comment]
Yes, the issue that was causing the data files to not be generated has been addressed. Thanks for reaching out!
