### ISSUE TITLE
cvescan on Xenial incorrectly labelling a number of CVEs as still unfixed.

### ISSUE THREAD

**Issue by VexVexVex** [canonical/sec-cvescan#86]
A number of CVEs that flag if one runs oscap against most recent OVAL data do not show in cvescan. Manually checking a few seems to indicate they're marked in the JSON DB as unfixed (so they don't flag on a normal run), but marked on the Ubuntu Security CVE tracker as fixed. 

`cvescan -p all` Results:
![image](https://user-images.githubusercontent.com/74362137/142507764-a81e8d40-9a23-4f30-8b49-85be6ce306b8.png)

`oscap oval eval <oval file> | grep true` results:
![image](https://user-images.githubusercontent.com/74362137/142509615-e9a8c757-d0d1-41ee-be69-beb0a9087f4d.png)

**Comment by setharnold** [comment]
I'm pretty sure those `Definition ...: true` messages are just debugging aids; the OVAL definitions involve several layers of indirection.

Try using the `--report report.html` argument as described at https://ubuntu.com/security/oval and see if the resulting `report.html` has the output you expect.

Thanks
