### ISSUE TITLE
cvescan gives  dpkg error on rhel8

### ISSUE THREAD

**Issue by leasharon** [canonical/sec-cvescan#91]
I installed cvescan on rhel8 but when i try to run the commad i get this error
Error: Failed to determine the local package count -- dpkg exited with code 2: dpkg-query: error: failed to open package info file '/var/lib/snapd/hostfs/var/lib/dpkg/status' for reading: No such file or directory

I installed cvescan by following the documentation at this link
https://snapcraft.io/install/cvescan/rhel

**Comment by mssalvatore** [comment]
I've been out of the loop on this for a while, but it looks like [the RHEL documentation](https://snapcraft.io/install/cvescan/rhel) is auto generated. CVEScan is only intended to scan an Ubuntu system.

You can use CVEScan on RHEL to scan a manifest file, but not to scan the RHEL system itself. See https://snapcraft.io/install/cvescan/rhel.
