### ISSUE TITLE
When using manifest, please provide option to specify suite

### ISSUE THREAD

**Issue by garyvdm** [canonical/sec-cvescan#92]
We don't install `update-manager-core` on our systems, and so to use cvescan from a manifest, we have to add a fake update-manager-core line to end of the manifest.

It would be nice to be able to specify the suite from the command line, something like:

    cvescan --manifest image_manifest.txt --suite focal

**Comment by dodys** [comment]
Please check #52 and #54. I will be closing this issue based on that, even though v3.0 never got published.

Nevertheless, do note we don't currently have the resources to give cvescan the attention it deserves, and in the meantime we continue improving our OVAL data.
I don't see us returning to cvescan in any real way soon, so please don't invest much time into it, I don't think we'll be able to reciprocate.

Thanks

**Comment by garyvdm** [comment]
Noted. Thank you.
